### ISSUE TITLE
Add Team Page

### ISSUE THREAD

**Issue by ChingChang9** [ChingChang9/PlantForever#1]
- Add people to the team page in Team.vue
- Uncomment line 10 ~ 18 and remove line 9 in App.vue
- For profile pictures, just use a random picture as a placeholder, we don't have any photos yet

> Marmik Patel - Founding President
> Marmik founded PlantForever in 2017 to create change. After learning about the limited time we have until the climate crisis poses irreversible global changes, Marmik took the initiative and began planting trees. Since then, Marmik has transformed a mere idea into a fully functioning organization; he assembled a team, launched city-wide tree planting initiatives, created local partnerships, and organized platforms to spread awareness. Marmik is proud of his city’s urban forest but knows it can expand.
> Now 17, Marmik aims to develop PlantForever internationally, spreading awareness and encouraging vast tree-canopy expansion in urban areas. He intends to inspire a movement empowering individuals to take action globally.

> Pedro Almeida - Vice President of Human Resources
> Pedro, now 17 is looking forward to his final year before post-secondary school where he will focus on his schooling as well as assisting the executive team to expand PlantForever as far as possible, by advancing communication between members as well as with people outside of the organization. He assisted the team in large events as well as messages to organizations that have aided PlantForever for his time here.

> Fatima Shamas - VP of social media
> Fatima joined PlantForever in 2018 as a volunteer, but later became part of the team in hopes of spreading awareness through social media. Her goal remains the same: to educate and inform people about climate change and help them to make changes within their lifestyle to combat it.

> Ching Chang – Vice President of IT
> As a 17 years old environmentalist, Ching joined PlantForever with the incentive of combating climate change and urban deforestation. With a passion for web developing, Ching is looking forward to not only maximize the ways that people can reach out to PlantForever from everywhere in the world, but to also make the process as simple as possible.

> Vanshaj Upadhyay - VP of Merchandise
> At 16 years old, Vanshaj joined the PF team almost at the very beginning, when things were first starting to fall in place. He enjoys working at PF because he is interested in environmental matters and taking care of the planet. Vanshaj’s goal at PlantForever is to battle pollution and climate change through the plantation of trees. Vanshaj is dedicated to the PlantForever mission.

> Eric Li - Photographer
> Eric initially joined PlantForever as a volunteer, helping the team with small photoshop tasks. Having a hobby in taking pictures, he officially joined the PF team in mid-2019 as the official photographer. He now works with all team members, taking photos during planting events.

**Comment by Voovs** [comment]
Sounds good. I'd like to try this one
