### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ChingChang9** [ChingChang9/PlantForever#2]
- Add information about what PlantForever does and how you can contribute to the organization
- Have a more detailed guide on how to contribute to the code

**Comment by Voovs** [comment]
Working on it

**Comment by nmeurer** [comment]
Workin' on it!

**Comment by nmeurer** [comment]
Do you mind telling a bit about PlantForever?

**Comment by nmeurer** [comment]
Made a PR (first "real issue" I've done)
